// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgwckzdrishieifyrjit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impnd2NremRyaXNoaWVpZnlyaml0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNTU4OTQsImV4cCI6MjA1OTczMTg5NH0.CtlwpzRT8tikCxYhT38rDSnfjSEoZYpUueXHQJIySw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);